version: "3.7"

services:
    database_ignite:
        image: postgres
        container_name: database_ignite
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=rentx
    app:
        build: .
        container_name: rentx
        restart: always
        command: yarn dev
        ports:
            - 3333:3333
        volumes: 
            - .:/usr/app
            - ./node_modules:/app/node_modules
        depends_on:
            - database_ignite